from fpdf import FPDF
import datetime
import os
from .parser import ArchieParser

class ArchieReport(FPDF):
    def header(self):
        # Logo placeholder
        self.set_font('helvetica', 'B', 20)
        self.set_text_color(99, 102, 241) # Indigo
        self.cell(0, 10, 'ARCHIE – THE WEB BUTLER', ln=True, align='L')
        self.set_font('helvetica', 'I', 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, 'AI Content Reconstruction Audit Report', ln=True, align='L')
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('helvetica', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by Archie Assistant | {datetime.datetime.now().strftime("%Y-%m-%d")}', align='C')

class ReportGenerator:
    @staticmethod
    def generate_audit_report(project_id: str, output_path: str):
        data = ArchieParser.get_project(project_id)
        if not data or "results" not in data:
            return {"error": "Project results not found"}

        res = data["results"]
        audit = res["audit"]

        pdf = ArchieReport()
        pdf.add_page()
        
        # Site Summary
        pdf.set_font('helvetica', 'B', 16)
        pdf.set_text_color(0, 0, 0)
        pdf.cell(0, 10, f'Audit Results: {data["url"]}', ln=True)
        pdf.ln(5)

        # Stark Contrast Section (The "Pitch")
        pdf.set_fill_color(99, 102, 241)
        pdf.set_text_color(255, 255, 255)
        pdf.set_font('helvetica', 'B', 12)
        pdf.cell(0, 10, '  THE LEGACY DEBT ANALYSIS', ln=True, fill=True)
        
        pdf.set_text_color(0, 0, 0)
        pdf.ln(5)
        pdf.set_font('helvetica', '', 10)
        
        stats = [
            ("Total Legacy Pages Found", str(audit["total_pages"])),
            ("Broken Links (404s)", str(len(res.get("broken_links", [])))),
            ("Duplicate Page Titles", str(audit["duplicate_titles"])),
            ("Thin Content Pages (<100 words)", str(audit["thin_content_pages"])),
            ("Total Media Assets", str(len(res.get("media", []))))
        ]

        for label, value in stats:
            pdf.set_font('helvetica', 'B', 10)
            pdf.cell(80, 8, label)
            pdf.set_font('helvetica', '', 10)
            pdf.cell(0, 8, value, ln=True)

        pdf.ln(10)
        
        # Recommendations
        pdf.set_fill_color(240, 240, 240)
        pdf.set_font('helvetica', 'B', 12)
        pdf.cell(0, 10, '  STRATEGIC RECOMMENDATIONS', ln=True, fill=True)
        pdf.ln(5)
        pdf.set_font('helvetica', '', 10)
        
        recommendations = [
            "1. Consolidate the duplicate title pages into semantic clusters.",
            "2. Modernize 100% of media assets to WebP via the Archie Canva Bridge.",
            "3. Optimize 'Thin Content' pages using Archie's Narrative Synthesis engine.",
            "4. Establish deep-link redirects for the 42 identifying broken links."
        ]
        
        for rec in recommendations:
            pdf.multi_cell(0, 8, rec)
        
        pdf.output(output_path)
        return {"path": output_path}
